# Generated by Django 4.1.3 on 2022-12-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="group", unique_together=set(),),
        migrations.AddField(
            model_name="group",
            name="datetime",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="group",
            name="img_url",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="group",
            name="tag",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="group", unique_together={("name", "datetime")},
        ),
        migrations.RemoveField(model_name="group", name="location",),
    ]
