# Generated by Django 4.1.3 on 2022-12-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('img_url', models.CharField(max_length=256, null=True)),
                ('description', models.CharField(max_length=256)),
                ('tag', models.CharField(max_length=512, null=True)),
            ],
        ),
    ]
