# Generated by Django 4.1.3 on 2023-01-15 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_username_alter_post_author"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="username",),
    ]
